# Generated by Django 4.2.5 on 2023-09-29 01:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
            ],
        ),
    ]
