# Generated by Django 4.2.5 on 2023-09-29 02:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.ImageField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='HNG_Videos'),
        ),
    ]
