# Generated by Django 4.2.5 on 2023-09-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='transcipt',
            field=models.TextField(blank=True, default='null', null=True),
        ),
    ]
